#!/bin/sh
set -e


case $1 in 
        remove|purge|abort-install|disappear)

                resp=$(lliurex-sgbd --db_is_present lliurex-moodle)
                if [ "$resp" = "YES" ]; then

                        lliurex-sgbd --remove lliurex-moodle
                        
                fi
                 
	           ;;
        *)
                echo "Nothing to do"
                ;; 
esac

#DEBHELPER#

exit 0
