<?php
 # This file has been generated by debconf
 # You can find a commented config file in /usr/share/doc/moodle/
 include("/etc/moodle/debian-db.php");
 unset($CFG);
 $CFG = new stdClass();

 $CFG->dbtype = $dbtype;
 $CFG->dbhost = 'localhost';
 $CFG->dbname = $dbname;
 $CFG->dbuser = $dbuser;
 $CFG->dbpass = $dbpass;
 $CFG->prefix = 'mdl_';

 $CFG->wwwroot = 'http://moodle';
 $CFG->dirroot = '/usr/share/moodle';
 $CFG->dataroot = '/var/lib/moodle';
 $CFG->directorypermissions = 0750;
 $CFG->admin = 'admin';

 $CFG->pathtodu = '/usr/bin/du';
 $CFG->unzip = '/usr/bin/unzip';
 $CFG->zip = '/usr/bin/zip';

 $CFG->respectsessionsettings = true;

 # For improved security, make sure html purifier is used.
 $CFG->enablehtmlpurifier = true;

        if (file_exists("$CFG->dirroot/lib/setup.php"))  {       // Do not edit
                include_once("$CFG->dirroot/lib/setup.php");
        } else {
                if ($CFG->dirroot == dirname(__FILE__)) {
                        echo "<p>Could not find this file: $CFG->dirroot/lib/setup.php</p>";
                        echo "<p>Are you sure all your files have been uploaded?</p>";
                } else {
                        echo "<p>Error detected in config.php</p>";
                        echo "<p>Error in: \$CFG->dirroot = '$CFG->dirroot';</p>";
                        echo "<p>Try this: \$CFG->dirroot = '".dirname(__FILE__)."';</p>";
                }
                die;
        }
// MAKE SURE WHEN YOU EDIT THIS FILE THAT THERE ARE NO SPACES, BLANK LINES,
// RETURNS, OR ANYTHING ELSE AFTER THE TWO CHARACTERS ON THE NEXT LINE.
?>
